[workspace]
resolver = "2"

members = [
    "projects/to_byte_slice",
    "projects/discriminated_union",
    "projects/simple_server",
    "projects/maybe",
    "projects/fizzbuzz_iterator",
    "projects/gzip_roundtrip",
    "projects/simple_snippets",
    "projects/traffic_light",
]
